//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.component.ui;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.component.ToastComponent_;

public final class FriendDetailComponent_
    extends FriendDetailComponent
{

    private Context context_;

    private FriendDetailComponent_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ll_user_detail_header_show_realname = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.ll_user_detail_header_show_realname));
        main_header_right_btn = ((ImageView) findViewById(cn.sx.decentworld.R.id.main_header_right_btn));
        main_header_left_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.main_header_left_tv));
        ll_user_detail_header_modification = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_user_detail_header_modification));
        tv_user_detail_header_remark = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_user_detail_header_remark));
        tv_user_detail_header_dw = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_user_detail_header_dw));
        ll_user_detail_header_remark = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_user_detail_header_remark));
        tv_user_detail_header_realname = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_user_detail_header_realname));
        ll_user_detail_header_refresh = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_user_detail_header_refresh));
        main_header_title = ((TextView) findViewById(cn.sx.decentworld.R.id.main_header_title));
        iv_user_detail_header_camera = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_user_detail_header_camera));
        iv_user_detailed_header_recharge = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_user_detailed_header_recharge));
        tv_user_detail_header_show = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_user_detail_header_show));
        main_header_left = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.main_header_left));
        iv_user_detail_header_edit_sign = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_user_detail_header_edit_sign));
        iv_user_detailed_header_setting = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_user_detailed_header_setting));
        main_header_right_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.main_header_right_tv));
        ll_user_detail_header_dw = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_user_detail_header_dw));
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        context = context_;
        if (context_ instanceof Activity) {
            activity = ((Activity) context_);
        }
        toast = ToastComponent_.getInstance_(context_);
    }

    public static FriendDetailComponent_ getInstance_(Context context) {
        return new FriendDetailComponent_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
