//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ChoceAndTakePictureComponent_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.LoginComponent_;
import cn.sx.decentworld.component.ui.MainFragmentComponent_;
import cn.sx.decentworld.component.ui.MeComponent_;
import cn.sx.decentworld.network.request.GetUserInfo_;
import cn.sx.decentworld.network.request.SetFriendInfo_;
import cn.sx.decentworld.network.request.SetUserInfo_;
import cn.sx.decentworld.widget.FloatScrollView;
import cn.sx.decentworld.widget.HackyViewPager;
import cn.sx.decentworld.widget.ListViewForScrollView;
import cn.sx.decentworld.widget.ScrollLayout;

public final class ChatFragment_
    extends ChatFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        meComponent = MeComponent_.getInstance_(getActivity());
        toast = ToastComponent_.getInstance_(getActivity());
        setFriendInfo = SetFriendInfo_.getInstance_(getActivity());
        loginComponent = LoginComponent_.getInstance_(getActivity());
        setUserInfo = SetUserInfo_.getInstance_(getActivity());
        choceAndTakePictureComponent = ChoceAndTakePictureComponent_.getInstance_(getActivity());
        getUserInfo = GetUserInfo_.getInstance_(getActivity());
        mainFragmentComponent = MainFragmentComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        fragment_chat_contact_sv = ((FloatScrollView) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_sv));
        tv_chat_me_sign = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_sign));
        fragment_chat_contact_header = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_header));
        chat_scrollLayout = ((ScrollLayout) findViewById(cn.sx.decentworld.R.id.chat_scrollLayout));
        menu_tab3_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab3_tv));
        menu_tab1_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab1_iv));
        tv_chat_me_edit = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_edit));
        main_bottom_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.main_bottom_ll));
        interesting_group_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.interesting_group_ll));
        menu_tab4_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab4_tv));
        tvTitle = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_header_title));
        new_friends_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.new_friends_ll));
        group_chat_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.group_chat_ll));
        ll_chat_me_user_detail = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_chat_me_user_detail));
        tv_chat_me_introduce = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_introduce));
        menu_tab_2 = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_2));
        unreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_unread_msg_number));
        rl_error_item = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_error_item));
        fragment_chat_contact_lv = ((ListViewForScrollView) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_lv));
        menu_tab_3 = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_3));
        menu_tab2_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab2_tv));
        menu_tab_4 = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_4));
        menu_tab4_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab4_iv));
        fragment_contact_choice_ll_child = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_contact_choice_ll_child));
        tv_chat_me_wealth = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_wealth));
        ll_contact_list_recommend = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_contact_list_recommend));
        relTitle = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.chat_room_title_root));
        iv_chat_me_avatar = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_chat_me_avatar));
        ll_contact_list_invite = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_contact_list_invite));
        btn_chat_me_send_msg = ((Button) findViewById(cn.sx.decentworld.R.id.btn_chat_me_send_msg));
        ll_contact_list_guarantee = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_contact_list_guarantee));
        fragment_chat_chat_lv = ((ListView) findViewById(cn.sx.decentworld.R.id.fragment_chat_chat_lv));
        tv_chat_me_worth = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_worth));
        menu_tab2_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab2_iv));
        fragment_contact_choice_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_contact_choice_ll));
        tv_chat_me_name = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_name));
        errorText = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_connect_errormsg));
        ll_chat_me_chat_room = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_chat_me_chat_room));
        new_friends_ll_unread_msg_number = ((TextView) findViewById(cn.sx.decentworld.R.id.new_friends_ll_unread_msg_number));
        mPager = ((HackyViewPager) findViewById(cn.sx.decentworld.R.id.vp_near_card_detail_pager));
        menu_tab1_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_tv));
        menu_tab3_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab3_iv));
        tv_chat_me_school = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_chat_me_school));
        menu_tab_1 = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_1));
        ivSearch = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_search));
        {
            View view = findViewById(cn.sx.decentworld.R.id.btn_chat_me_send_msg);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.sendMsg();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.tv_chat_me_edit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.editUserInfo(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.ll_chat_me_chat_room);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.editRoomList();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_chat_find_group_interested);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.fragment_chat_find_group_interested();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_chat_find_work_circle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.fragment_chat_find_work_circle();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.group_chat_ll);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.showGroupChat();
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(cn.sx.decentworld.R.id.fragment_chat_chat_lv));
            if (view!= null) {
                view.setOnItemLongClickListener(new OnItemLongClickListener() {


                    @Override
                    public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                        show_delete_dialog(position);
                        return true;
                    }

                }
                );
            }
        }
        ((MeComponent_) meComponent).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        ((SetFriendInfo_) setFriendInfo).afterSetContentView_();
        ((LoginComponent_) loginComponent).afterSetContentView_();
        ((SetUserInfo_) setUserInfo).afterSetContentView_();
        ((ChoceAndTakePictureComponent_) choceAndTakePictureComponent).afterSetContentView_();
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        ((MainFragmentComponent_) mainFragmentComponent).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.main_layout_chat, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ChatFragment_.FragmentBuilder_ builder() {
        return new ChatFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ChatFragment build() {
            ChatFragment_ fragment_ = new ChatFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
