//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.MainFragmentComponent_;
import cn.sx.decentworld.flingswipe.SwipeFlingAdapterView;
import cn.sx.decentworld.network.request.GetStrangerInfo_;
import cn.sx.decentworld.network.request.GetUserInfo_;
import cn.sx.decentworld.widget.ScrollLayout;
import com.handmark.pulltorefresh.library.PullToRefreshListView;

public final class StrangerFragment_
    extends StrangerFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        getStrangerInfo = GetStrangerInfo_.getInstance_(getActivity());
        toast = ToastComponent_.getInstance_(getActivity());
        getUserInfo = GetUserInfo_.getInstance_(getActivity());
        mainFragmentComponent = MainFragmentComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        fragment_stranger_tab = ((ImageView) findViewById(cn.sx.decentworld.R.id.fragment_stranger_tab));
        near_stranger_scrollLayout = ((ScrollLayout) findViewById(cn.sx.decentworld.R.id.near_stranger_scrollLayout));
        lvStrangerInfo = ((ListView) findViewById(cn.sx.decentworld.R.id.fragment_stranger_chat_lv));
        ll_stranger_near_root = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.root_ll_stranger_near));
        relStranger = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.root_main_layout_stranger));
        iv_fragment_stranger_near_tab = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_fragment_stranger_near_tab));
        flingContainer = ((SwipeFlingAdapterView) findViewById(cn.sx.decentworld.R.id.fragment_stranger_near_lv));
        llStrangerNear = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.root_ll_stranger_near));
        lvNearStranger = ((PullToRefreshListView) findViewById(cn.sx.decentworld.R.id.lv_near_stranger));
        tvRefresh = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_refresh));
        tvSelect = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_select));
        tvTitle = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_header_title));
        stranger_scrollLayout = ((ScrollLayout) findViewById(cn.sx.decentworld.R.id.stranger_scrollLayout));
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_stranger_tab);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        StrangerFragment_.this.fragment_stranger_tab();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.iv_near_buttons_info);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        StrangerFragment_.this.buttonsInfo();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.iv_fragment_stranger_near_tab);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        StrangerFragment_.this.ll_fragment_stranger_near_tab();
                    }

                }
                );
            }
        }
        ((GetStrangerInfo_) getStrangerInfo).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        ((MainFragmentComponent_) mainFragmentComponent).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.main_layout_stranger, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static StrangerFragment_.FragmentBuilder_ builder() {
        return new StrangerFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public StrangerFragment build() {
            StrangerFragment_ fragment_ = new StrangerFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
