//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ChoceAndTakePictureComponent_;
import cn.sx.decentworld.component.ui.MainFragmentComponent_;
import cn.sx.decentworld.component.ui.MeComponent_;
import cn.sx.decentworld.widget.FloatScrollView;
import cn.sx.decentworld.widget.ListViewForScrollView;
import cn.sx.decentworld.widget.ScrollLayout;

public final class ChatFragment_
    extends ChatFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        picture = ChoceAndTakePictureComponent_.getInstance_(getActivity());
        mainFragmentComponent = MainFragmentComponent_.getInstance_(getActivity());
        meComponent = MeComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        unreadAddressLable = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab2_unread_msg_number));
        fragment_chat_contact_lv = ((ListViewForScrollView) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_lv));
        fragment_contact_choice_ll_child = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_contact_choice_ll_child));
        menu_tab1_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab1_iv));
        menu_tab4_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab4_tv));
        unreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_unread_msg_number));
        fragment_contact_choice_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_contact_choice_ll));
        chat_me_for_work_root = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.chat_me_for_work_root));
        main_user_detail_header_root = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.main_user_detail_header_root));
        fragment_chat_contact_sv = ((FloatScrollView) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_sv));
        fragment_chat_chat_lv = ((ListView) findViewById(cn.sx.decentworld.R.id.fragment_chat_chat_lv));
        menu_tab2_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab2_iv));
        menu_tab4_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab4_iv));
        item_work_comment_root = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.item_work_comment_root));
        main_bottom_ll = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.main_bottom_ll));
        menu_tab2_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab2_tv));
        chat_scrollLayout = ((ScrollLayout) findViewById(cn.sx.decentworld.R.id.chat_scrollLayout));
        progressBar = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.progress_bar));
        fragment_chat_contact_header = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_header));
        new_friends_ll_unread_msg_number = ((TextView) findViewById(cn.sx.decentworld.R.id.new_friends_ll_unread_msg_number));
        menu_tab3_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab3_tv));
        menu_tab1_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_tv));
        errorText = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_connect_errormsg));
        menu_tab3_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab3_iv));
        errorItem = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_error_item));
        {
            View view = findViewById(cn.sx.decentworld.R.id.menu_tab_3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.tab3();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.interesting_group_ll);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.showGroup();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.new_friends_ll);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.do_someth();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.group_chat_ll);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.showGroupChat();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_chat_find_group_interested);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.fragment_chat_find_group_interested();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.menu_tab_2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.tab2();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_chat_find_work_circle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.fragment_chat_find_work_circle();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.menu_tab_1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.tab1();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.fragment_chat_contact_search);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.fragment_chat_contact_search();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.menu_tab_4);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatFragment_.this.tab4();
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(cn.sx.decentworld.R.id.fragment_chat_chat_lv));
            if (view!= null) {
                view.setOnItemLongClickListener(new OnItemLongClickListener() {


                    @Override
                    public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                        show_delete_dialog(position);
                        return true;
                    }

                }
                );
            }
        }
        ((ChoceAndTakePictureComponent_) picture).afterSetContentView_();
        ((MainFragmentComponent_) mainFragmentComponent).afterSetContentView_();
        ((MeComponent_) meComponent).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.main_layout_chat, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ChatFragment_.FragmentBuilder_ builder() {
        return new ChatFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ChatFragment build() {
            ChatFragment_ fragment_ = new ChatFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
