//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.stranger;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.flingswipe.SwipeFlingAdapterView;
import cn.sx.decentworld.network.request.GetStrangerInfo_;

public final class StrangerCardFragment_
    extends StrangerCardFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        getStrangerInfo = GetStrangerInfo_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tvRefresh = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_refresh));
        flingContainer = ((SwipeFlingAdapterView) findViewById(cn.sx.decentworld.R.id.fragment_stranger_near_lv));
        ((GetStrangerInfo_) getStrangerInfo).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_near_card, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static StrangerCardFragment_.FragmentBuilder_ builder() {
        return new StrangerCardFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public StrangerCardFragment build() {
            StrangerCardFragment_ fragment_ = new StrangerCardFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
