//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.stranger;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import cn.sx.decentworld.R.layout;
import com.handmark.pulltorefresh.library.PullToRefreshListView;

public final class StrangerListFragment_
    extends StrangerListFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        lvNearStranger = ((PullToRefreshListView) findViewById(cn.sx.decentworld.R.id.lv_stranger_near));
        relLv = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rel_lv));
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_near_list, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static StrangerListFragment_.FragmentBuilder_ builder() {
        return new StrangerListFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public StrangerListFragment build() {
            StrangerListFragment_ fragment_ = new StrangerListFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
