//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.setting;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import cn.sx.decentworld.R.layout;

public final class AdvanceSettingFragment_
    extends AdvanceSettingFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        ll_advance_setting_root = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_advance_setting_root));
        iv_advance_ifClose_voice_stranger = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_advance_ifClose_voice_stranger));
        iv_advance_setting_push_system = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_advance_setting_push_system));
        iv_advance_setting_acceptCheckPush = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_advance_setting_acceptCheckPush));
        iv_advance_ifClose_voice_friend = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_advance_ifClose_voice_friend));
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.activity_advance_setting, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static AdvanceSettingFragment_.FragmentBuilder_ builder() {
        return new AdvanceSettingFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public AdvanceSettingFragment build() {
            AdvanceSettingFragment_ fragment_ = new AdvanceSettingFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
