CREATE TABLE msgTop (time TEXT, Id INTEGER PRIMARY KEY AUTOINCREMENT, userID TEXT, otherID TEXT);
CREATE TABLE noDisturb (userID TEXT, otherID TEXT, Id INTEGER PRIMARY KEY AUTOINCREMENT);
DROP TABLE toplist;
DROP TABLE noremindlist;