DROP TABLE msgTop;
DROP TABLE noDisturb;
DROP TABLE chatbg;
CREATE TABLE chatSetting (Id INTEGER PRIMARY KEY AUTOINCREMENT, msgTopTime TEXT, chatBg TEXT, isMsgNoDisturb INTEGER, otherID TEXT, isMsgTop INTEGER, userID TEXT);