//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity.discover;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.TitleBar_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.MomentNetRequest_;
import cn.sx.decentworld.widget.ExpandGridView;
import cn.sx.decentworld.widget.RecorderButton;
import cn.sx.decentworld.widget.SlipButton;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class PublishMomentActivity_
    extends PublishMomentActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_publish_moment);
    }

    private void init_(Bundle savedInstanceState) {
        titleBar = TitleBar_.getInstance_(this);
        momentNetRequest = MomentNetRequest_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tv_publish_friends_circle_state = ((TextView) findViewById(id.tv_publish_friends_circle_state));
        ll_publish_friends_circle_voice = ((LinearLayout) findViewById(id.ll_publish_friends_circle_voice));
        tv_publish_friends_circle_voice_path = ((TextView) findViewById(id.tv_publish_friends_circle_voice_path));
        ll_publish_friends_circle_state = ((RelativeLayout) findViewById(id.ll_publish_friends_circle_state));
        gv_publish_friends_circle_image = ((ExpandGridView) findViewById(id.gv_publish_friends_circle_image));
        et_publish_friends_circle_txt = ((EditText) findViewById(id.et_publish_friends_circle_txt));
        tv_publish_friends_circle_info = ((TextView) findViewById(id.tv_publish_friends_circle_info));
        ll_publish_friends_circle_see = ((LinearLayout) findViewById(id.ll_publish_friends_circle_see));
        btn_publish_friends_circle_record_voice = ((RecorderButton) findViewById(id.btn_publish_friends_circle_record_voice));
        main_header_left = ((LinearLayout) findViewById(id.main_header_left));
        sb_publish_friends_circle_send = ((SlipButton) findViewById(id.sb_publish_friends_circle_send));
        btn_publish_friends_circle_see = ((Button) findViewById(id.btn_publish_friends_circle_see));
        ((TitleBar_) titleBar).afterSetContentView_();
        ((MomentNetRequest_) momentNetRequest).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static PublishMomentActivity_.IntentBuilder_ intent(Context context) {
        return new PublishMomentActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PublishMomentActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PublishMomentActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
