//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.LinearLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.FriendDetailComponent_;
import cn.sx.decentworld.widget.CircularImage;
import cn.sx.decentworld.widget.ListViewForScrollView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.handmark.pulltorefresh.library.PullToRefreshScrollView;

public final class FriendDetailActivity_
    extends FriendDetailActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_friend_detail);
    }

    private void init_(Bundle savedInstanceState) {
        friendDetailComponent = FriendDetailComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        sv_friend_detail_pull_to_refresh = ((PullToRefreshScrollView) findViewById(id.sv_friend_detail_pull_to_refresh));
        tv_user_detail_header_age = ((TextView) findViewById(id.tv_user_detail_header_age));
        tv_user_detail_header_asset = ((TextView) findViewById(id.tv_user_detail_header_asset));
        circularImage = ((CircularImage) findViewById(id.iv_user_detail_info_avatar));
        tv_user_detail_header_value = ((TextView) findViewById(id.tv_user_detail_header_value));
        main_user_detail_header_root = ((LinearLayout) findViewById(id.main_user_detail_header_root));
        tv_user_detail_header_location = ((TextView) findViewById(id.tv_user_detail_header_location));
        lv_friend_detail_work_circle = ((ListViewForScrollView) findViewById(id.lv_friend_detail_work_circle));
        tv_user_detail_header_sign = ((TextView) findViewById(id.tv_user_detail_header_sign));
        tv_user_detail_header_nickname = ((TextView) findViewById(id.tv_user_detail_header_nickname));
        ((FriendDetailComponent_) friendDetailComponent).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static FriendDetailActivity_.IntentBuilder_ intent(Context context) {
        return new FriendDetailActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, FriendDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public FriendDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
