//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.benefit;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;

public final class BenefitFragment_
    extends BenefitFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tv_benefit_3 = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_benefit_3));
        ll_benefit_titile_switch_bg = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_benefit_titile_switch_bg));
        tv_benefit_2 = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_benefit_2));
        tv_benefit_1 = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_benefit_1));
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_benefit, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static BenefitFragment_.FragmentBuilder_ builder() {
        return new BenefitFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public BenefitFragment build() {
            BenefitFragment_ fragment_ = new BenefitFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
