//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.benefit;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.GetUserInfo_;
import cn.sx.decentworld.widget.ListViewForScrollView;

public final class CashBenefitFragment_
    extends CashBenefitFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(getActivity());
        getUserInfo = GetUserInfo_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tv_cash_benefit_not_small = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_not_small));
        tv_cash_benefit_not_draw = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_not_draw));
        tv_cash_benefit_total_small = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_total_small));
        ll_cash_benefit_remind = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.ll_cash_benefit_remind));
        mDrawCash = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_cash_benefit_draw));
        tv_cash_benefit_not_big = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_not_big));
        tv_cash_benefit_back_big = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_back_big));
        tv_cash_benefit_back_small = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_back_small));
        listView = ((ListViewForScrollView) findViewById(cn.sx.decentworld.R.id.lv_cash_benefit));
        tv_cash_benefit_autoTransfer = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_autoTransfer));
        tv_cash_benefit_alipay = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_alipay));
        tv_cash_benefit_total_big = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_total_big));
        tv_cash_benefit_wx = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_wx));
        ((ToastComponent_) toast).afterSetContentView_();
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_cash_benefit, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static CashBenefitFragment_.FragmentBuilder_ builder() {
        return new CashBenefitFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public CashBenefitFragment build() {
            CashBenefitFragment_ fragment_ = new CashBenefitFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
