//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.benefit;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;

public final class VirtualCurrencyFragment_
    extends VirtualCurrencyFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tvBankCard = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_vc_band_bankCard));
        tvSetBankCard = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_vc_band_card));
        mTvBigWealth = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_cash_benefit_not_draw));
        mDrawWealth = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_vc_draw));
        mTvWealth = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_vc_wealth));
        mTvWorth = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_vc_worth));
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_virtual_currency, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static VirtualCurrencyFragment_.FragmentBuilder_ builder() {
        return new VirtualCurrencyFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public VirtualCurrencyFragment build() {
            VirtualCurrencyFragment_ fragment_ = new VirtualCurrencyFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
