//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ui.MainFragmentComponent_;
import com.handmark.pulltorefresh.library.PullToRefreshListView;

public final class NewsFragment_
    extends NewsFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        component = MainFragmentComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        main_layout_news_lv = ((PullToRefreshListView) findViewById(cn.sx.decentworld.R.id.main_layout_news_lv));
        add_topic_detail = ((ImageView) findViewById(cn.sx.decentworld.R.id.add_topic_detail));
        {
            View view = findViewById(cn.sx.decentworld.R.id.add_topic_detail);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewsFragment_.this.todetail();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(cn.sx.decentworld.R.id.icon_to_setnickname);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewsFragment_.this.show_fra_set_nick();
                    }

                }
                );
            }
        }
        ((MainFragmentComponent_) component).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.main_layout_news, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static NewsFragment_.FragmentBuilder_ builder() {
        return new NewsFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public NewsFragment build() {
            NewsFragment_ fragment_ = new NewsFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
