//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.main;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.GetUserInfo_;

public final class ConversationFragment_
    extends ConversationFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        getUserInfo = GetUserInfo_.getInstance_(getActivity());
        toast = ToastComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        fragment_chat_chat_lv = ((ListView) findViewById(cn.sx.decentworld.R.id.fragment_chat_chat_lv));
        ivSearch = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_search));
        tvTitle = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_header_title));
        tv_connect_errormsg = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_connect_errormsg));
        rl_fragment_chat_chat_error = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_fragment_chat_chat_error));
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_main_conversation, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ConversationFragment_.FragmentBuilder_ builder() {
        return new ConversationFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ConversationFragment build() {
            ConversationFragment_ fragment_ = new ConversationFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
