//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.main;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;

public final class FindFragment_
    extends FindFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        rl_find_interest_group = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_find_interest_group));
        rl_find_works_circle = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_find_works_circle));
        tvTitle = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_header_title));
        rl_find_friends_circle = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.rl_find_friends_circle));
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_main_find, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static FindFragment_.FragmentBuilder_ builder() {
        return new FindFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public FindFragment build() {
            FindFragment_ fragment_ = new FindFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
