//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.bean.manager.DWMMessageManager_;
import cn.sx.decentworld.component.ChoceAndTakePictureComponent_;
import cn.sx.decentworld.component.KeyboardComponent_;
import cn.sx.decentworld.component.TitleBar_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.ChatComponent_;
import cn.sx.decentworld.component.ui.ChatRoomChatComponent_;
import cn.sx.decentworld.network.request.GetRoomInfo_;
import cn.sx.decentworld.network.request.SetRoomInfo_;
import cn.sx.decentworld.widget.CircularImage;
import cn.sx.decentworld.widget.HorizontalListView;
import cn.sx.decentworld.widget.PasteEditText;
import cn.sx.decentworld.widget.RecorderButton;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.handmark.pulltorefresh.library.PullToRefreshListView;

public final class ChatRoomChatActivity_
    extends ChatRoomChatActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_chat_room_chat);
    }

    private void init_(Bundle savedInstanceState) {
        chatRoomChatComponent = ChatRoomChatComponent_.getInstance_(this);
        choceAndTakePictureComponent = ChoceAndTakePictureComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
        setRoomInfo = SetRoomInfo_.getInstance_(this);
        dwmMessageManager = DWMMessageManager_.getInstance_(this);
        chatComponent = ChatComponent_.getInstance_(this);
        titleBar = TitleBar_.getInstance_(this);
        KeyboardComponent = KeyboardComponent_.getInstance_(this);
        getRoomInfo = GetRoomInfo_.getInstance_(this);
    }

    private void afterSetContentView_() {
        ivFixed = ((ImageView) findViewById(id.iv_fixed));
        buttonSetModeKeyboard = ((Button) findViewById(id.btn_set_mode_keyboard));
        emojiIconContainer = ((LinearLayout) findViewById(id.ll_face_container));
        civ_chat_room_chat_owner_icon = ((CircularImage) findViewById(id.civ_chat_room_chat_owner_icon));
        edittext_layout = ((RelativeLayout) findViewById(id.edittext_layout));
        buttonSend = ((Button) findViewById(id.btn_send));
        buttonPressToSpeak = ((RecorderButton) findViewById(id.btn_press_to_speak));
        chat_room_imgList = ((HorizontalListView) findViewById(id.chat_room_imgList));
        expressionViewpager = ((ViewPager) findViewById(id.vPager));
        btnMore = ((Button) findViewById(id.btn_more));
        btnContainer = ((LinearLayout) findViewById(id.ll_btn_container));
        iv_emoticons_normal = ((ImageView) findViewById(id.iv_emoticons_normal));
        mEditTextContent = ((PasteEditText) findViewById(id.et_sendmessage));
        btn_set_mode_voice = ((Button) findViewById(id.btn_set_mode_voice));
        activity_chat_bg = ((ImageView) findViewById(id.activity_chat_bg));
        listView = ((PullToRefreshListView) findViewById(id.lv_chat_room_list));
        more = ((LinearLayout) findViewById(id.more));
        iv_emoticons_checked = ((ImageView) findViewById(id.iv_emoticons_checked));
        {
            View view = findViewById(id.btn_set_mode_voice);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatRoomChatActivity_.this.btn_set_mode_voice();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatRoomChatActivity_.this.back();
                    }

                }
                );
            }
        }
        ((ChatRoomChatComponent_) chatRoomChatComponent).afterSetContentView_();
        ((ChoceAndTakePictureComponent_) choceAndTakePictureComponent).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        ((SetRoomInfo_) setRoomInfo).afterSetContentView_();
        ((DWMMessageManager_) dwmMessageManager).afterSetContentView_();
        ((ChatComponent_) chatComponent).afterSetContentView_();
        ((TitleBar_) titleBar).afterSetContentView_();
        ((KeyboardComponent_) KeyboardComponent).afterSetContentView_();
        ((GetRoomInfo_) getRoomInfo).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ChatRoomChatActivity_.IntentBuilder_ intent(Context context) {
        return new ChatRoomChatActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ChatRoomChatActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ChatRoomChatActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
