//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.TitleBar_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.widget.ExpandGridView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class ChatSettingActivity_
    extends ChatSettingActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.chat_setting);
    }

    private void init_(Bundle savedInstanceState) {
        titleBar = TitleBar_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        iv_switch_top = ((ImageView) findViewById(id.iv_switch_top));
        iv_switch_ddisturb = ((ImageView) findViewById(id.iv_switch_no_disturb));
        rl_chat_details_set_bg = ((RelativeLayout) findViewById(id.rl_chat_details_set_bg));
        chat_setting_gridview = ((ExpandGridView) findViewById(id.chat_setting_gridview));
        rl_chat_details_empty_record = ((RelativeLayout) findViewById(id.rl_chat_details_empty_record));
        rl_chat_details_whistleblowing = ((RelativeLayout) findViewById(id.rl_chat_details_whistleblowing));
        {
            View view = findViewById(id.iv_switch_top);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.switchTop();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.iv_switch_no_disturb);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.switchNDisturb();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.rl_chat_details_set_bg);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.setChatBg();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.rl_chat_details_whistleblowing);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.whistleBlowing();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.setBack();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.rl_chat_details_empty_record);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ChatSettingActivity_.this.emptyRecord();
                    }

                }
                );
            }
        }
        ((TitleBar_) titleBar).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ChatSettingActivity_.IntentBuilder_ intent(Context context) {
        return new ChatSettingActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ChatSettingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ChatSettingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
