//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.ChatRoomInfoSettingAndGetting_;
import cn.sx.decentworld.widget.ScrollLayout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class ChatRoomAddThemeActivity_
    extends ChatRoomAddThemeActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_chatroom_add);
    }

    private void init_(Bundle savedInstanceState) {
        chatRoomInfoSettingAndGetting = ChatRoomInfoSettingAndGetting_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        etFee = ((EditText) findViewById(id.et_fee));
        rbContent = ((RadioButton) findViewById(id.rb_content));
        rbFixed = ((RadioButton) findViewById(id.rb_fixed));
        ivCover = ((ImageView) findViewById(id.iv_cover));
        btnFeeScaleSave = ((Button) findViewById(id.btn_fee_scale_save));
        tvFeeScale = ((TextView) findViewById(id.rb_fee_scale));
        ivBack = ((ImageView) findViewById(id.iv_back));
        tvSend = ((TextView) findViewById(id.tv_send));
        rgFeeContent = ((RadioGroup) findViewById(id.rg_content));
        tvPercent = ((TextView) findViewById(id.tv_percent));
        rbFeeScale = ((RadioButton) findViewById(id.rb_fee_scale));
        btnContentSave = ((Button) findViewById(id.btn_content_save));
        slFee = ((ScrollLayout) findViewById(id.sl_fee));
        etSubjectName = ((EditText) findViewById(id.tv_subj_name));
        llEdit = ((LinearLayout) findViewById(id.root_activity_edit));
        rgFeeScale = ((RadioGroup) findViewById(id.rg_fee_Scale));
        lvAddNewTheme = ((ListView) findViewById(id.lv_add_new_theme));
        ((ChatRoomInfoSettingAndGetting_) chatRoomInfoSettingAndGetting).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ChatRoomAddThemeActivity_.IntentBuilder_ intent(Context context) {
        return new ChatRoomAddThemeActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ChatRoomAddThemeActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ChatRoomAddThemeActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
