//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.SetUserInfo_;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class DrawCashSettingActivity_
    extends DrawCashSettingActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_draw_cash_setting);
    }

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(this);
        setUserInfo = SetUserInfo_.getInstance_(this);
    }

    private void afterSetContentView_() {
        etPwd1 = ((EditText) findViewById(id.et_draw_cash_setting_pwd1));
        etPwd = ((EditText) findViewById(id.et_draw_cash_setting_pwd));
        etAccount = ((EditText) findViewById(id.et_draw_cash_setting_account));
        btnPwdSubmit = ((Button) findViewById(id.btn_draw_cash_setting_pwd_submit));
        etAmount = ((EditText) findViewById(id.et_draw_cash_setting_amount));
        tvAccountName = ((TextView) findViewById(id.tv_draw_cash_setting_account));
        btnDraw = ((Button) findViewById(id.btn_draw_cash_setting_draw));
        btnAccountSubmit = ((Button) findViewById(id.btn_draw_cash_setting_account_submit));
        ((ToastComponent_) toast).afterSetContentView_();
        ((SetUserInfo_) setUserInfo).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static DrawCashSettingActivity_.IntentBuilder_ intent(Context context) {
        return new DrawCashSettingActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DrawCashSettingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DrawCashSettingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
