//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ChoceAndTakePictureComponent_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.GetUserInfo_;
import cn.sx.decentworld.network.request.SetUserInfo_;
import cn.sx.decentworld.widget.ListViewForScrollView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class EditUserInfoActivity_
    extends EditUserInfoActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_edit_user_info);
    }

    private void init_(Bundle savedInstanceState) {
        choceAndTakePictureComponent = ChoceAndTakePictureComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
        setUserInfo = SetUserInfo_.getInstance_(this);
        getUserInfo = GetUserInfo_.getInstance_(this);
    }

    private void afterSetContentView_() {
        iv_edit_user_info_icon_3 = ((ImageView) findViewById(id.iv_edit_user_info_icon_3));
        iv_edit_user_info_icon_1 = ((ImageView) findViewById(id.iv_edit_user_info_icon_1));
        tvFinish = ((TextView) findViewById(id.tv_finish));
        ll_edit_user_info_root = ((LinearLayout) findViewById(id.ll_edit_user_info_root));
        lv_edit_user_info = ((ListViewForScrollView) findViewById(id.lv_edit_user_info));
        ivBack = ((ImageView) findViewById(id.iv_back));
        sl_edit_user_info = ((ScrollView) findViewById(id.sl_edit_user_info));
        iv_edit_user_info_icon_2 = ((ImageView) findViewById(id.iv_edit_user_info_icon_2));
        ((ChoceAndTakePictureComponent_) choceAndTakePictureComponent).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        ((SetUserInfo_) setUserInfo).afterSetContentView_();
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static EditUserInfoActivity_.IntentBuilder_ intent(Context context) {
        return new EditUserInfoActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, EditUserInfoActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public EditUserInfoActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
