//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.RegisterComponent_;
import cn.sx.decentworld.widget.HackyViewPager;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class ExamineActivity_
    extends ExamineActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_examine);
    }

    private void init_(Bundle savedInstanceState) {
        registerComponent = RegisterComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tvName = ((TextView) findViewById(id.tv_name));
        vpExamine = ((HackyViewPager) findViewById(id.vp_examine));
        tvNoPass = ((TextView) findViewById(id.tv_nopass));
        tvSex = ((TextView) findViewById(id.tv_sex));
        tvPass = ((TextView) findViewById(id.tv_pass));
        tvOccupation = ((TextView) findViewById(id.tv_occupation_shortIntroduce));
        ivPass = ((ImageView) findViewById(id.iv_pass));
        tvCondition = ((TextView) findViewById(id.tv_condition));
        ivNoPass = ((ImageView) findViewById(id.iv_no_pass));
        llDots = ((LinearLayout) findViewById(id.ll_dots));
        etIntroduce = ((EditText) findViewById(id.et_introduce));
        tvIfEnter = ((TextView) findViewById(id.tv_ifEnter));
        ((RegisterComponent_) registerComponent).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ExamineActivity_.IntentBuilder_ intent(Context context) {
        return new ExamineActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ExamineActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ExamineActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
