//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.FriendDetailComponent_;
import cn.sx.decentworld.widget.CircularImage;
import cn.sx.decentworld.widget.HackyViewPager;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.handmark.pulltorefresh.library.PullToRefreshScrollView;

public final class FriendDetailActivity_
    extends FriendDetailActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_friend_info);
    }

    private void init_(Bundle savedInstanceState) {
        toast = ToastComponent_.getInstance_(this);
        friendDetailComponent = FriendDetailComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tv_friend_info_title = ((TextView) findViewById(id.tv_friend_info_title));
        ll_friend_info_work_circle = ((LinearLayout) findViewById(id.ll_friend_info_work_circle));
        rl_friend_info_root = ((RelativeLayout) findViewById(id.rl_friend_info_root));
        rl_friend_info_setting = ((RelativeLayout) findViewById(id.rl_friend_info_setting));
        iv_friend_info_avatar = ((CircularImage) findViewById(id.iv_friend_info_avatar));
        sl_friend_info_pullToRefresh = ((PullToRefreshScrollView) findViewById(id.sl_friend_info_pullToRefresh));
        iv_friend_info_tab = ((ImageView) findViewById(id.iv_friend_info_tab));
        ll_friend_info_detail = ((LinearLayout) findViewById(id.ll_friend_info_detail));
        vp_friend_info_pager = ((HackyViewPager) findViewById(id.vp_friend_info_pager));
        {
            View view = findViewById(id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FriendDetailActivity_.this.back();
                    }

                }
                );
            }
        }
        ((ToastComponent_) toast).afterSetContentView_();
        ((FriendDetailComponent_) friendDetailComponent).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static FriendDetailActivity_.IntentBuilder_ intent(Context context) {
        return new FriendDetailActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, FriendDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public FriendDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
