//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class InterestingGroupActivity_
    extends InterestingGroupActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_interesting_group);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        lv_group_distance_group = ((ListView) findViewById(cn.sx.decentworld.R.id.lv_group_distance_group));
        main_header_left_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.main_header_left_tv));
        main_header_right = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.main_header_right));
        main_header_left = ((LinearLayout) findViewById(cn.sx.decentworld.R.id.main_header_left));
        main_header_title = ((TextView) findViewById(cn.sx.decentworld.R.id.tv_header_title));
        sv_interesting_group_near = ((ScrollView) findViewById(cn.sx.decentworld.R.id.sv_interesting_group_near));
        lv_recommand_group = ((ListView) findViewById(cn.sx.decentworld.R.id.lv_recommand_group));
        {
            View view = findViewById(cn.sx.decentworld.R.id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InterestingGroupActivity_.this.click_back();
                    }

                }
                );
            }
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(cn.sx.decentworld.R.id.lv_recommand_group));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        recommand_item_click();
                    }

                }
                );
            }
        }
        dosometh();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static InterestingGroupActivity_.IntentBuilder_ intent(Context context) {
        return new InterestingGroupActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, InterestingGroupActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public InterestingGroupActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
