//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.MainFragmentComponent_;
import cn.sx.decentworld.widget.ExpandGridView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class InterestingGroupBuildActivity_
    extends InterestingGroupBuildActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activitiy_interesting_group_build);
    }

    private void init_(Bundle savedInstanceState) {
        component = MainFragmentComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        main_header_left_tv = ((TextView) findViewById(id.main_header_left_tv));
        build_iv_if_toshow_member = ((ImageView) findViewById(id.build_iv_if_toshow_member));
        gridView = ((ExpandGridView) findViewById(id.build_gv_members_inter_group));
        main_header_right = ((RelativeLayout) findViewById(id.main_header_right));
        build_tv_place_inter_group = ((TextView) findViewById(id.build_tv_place_inter_group));
        build_activity_interesting_group_item_info_root = ((LinearLayout) findViewById(id.build_activity_interesting_group_item_info_root));
        main_header_left = ((LinearLayout) findViewById(id.main_header_left));
        main_header_right_tv = ((TextView) findViewById(id.main_header_right_tv));
        main_header_right_btn = ((ImageView) findViewById(id.main_header_right_btn));
        build_group_name = ((TextView) findViewById(id.build_group_name));
        main_header_title = ((TextView) findViewById(id.tv_header_title));
        {
            View view = findViewById(id.rl_toshow_something);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InterestingGroupBuildActivity_.this.showsomething();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.build_rl_if_toshow_member);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InterestingGroupBuildActivity_.this.if_toshow();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InterestingGroupBuildActivity_.this.click_back();
                    }

                }
                );
            }
        }
        ((MainFragmentComponent_) component).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static InterestingGroupBuildActivity_.IntentBuilder_ intent(Context context) {
        return new InterestingGroupBuildActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, InterestingGroupBuildActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public InterestingGroupBuildActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
