//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.TitleBar_;
import cn.sx.decentworld.network.request.GetUserInfo_;
import cn.sx.decentworld.network.request.SetUserInfo_;
import cn.sx.decentworld.widget.CircularImage;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class MagnateWindowActivity_
    extends MagnateWindowActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_magnate_window);
    }

    private void init_(Bundle savedInstanceState) {
        titleBar = TitleBar_.getInstance_(this);
        getUserInfo = GetUserInfo_.getInstance_(this);
        setUserInfo = SetUserInfo_.getInstance_(this);
    }

    private void afterSetContentView_() {
        tv_magnate_to_other_total_revenue = ((TextView) findViewById(id.tv_magnate_to_other_total_revenue));
        tv_magnate_to_me_name = ((TextView) findViewById(id.tv_magnate_to_me_name));
        lv_magnate_to_other_names = ((ListView) findViewById(id.lv_magnate_to_other_names));
        iv_magnate_to_me_avatar = ((CircularImage) findViewById(id.iv_magnate_to_me_avatar));
        btn_magnate_window_to_me_delete = ((Button) findViewById(id.btn_magnate_window_to_me_delete));
        btn_magnate_window_to_me_add = ((Button) findViewById(id.btn_magnate_window_to_me_add));
        btn_magnate_window_to_me_modify = ((Button) findViewById(id.btn_magnate_window_to_me_modify));
        {
            View view = findViewById(id.btn_magnate_window_to_me_delete);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MagnateWindowActivity_.this.deleteMagnate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_magnate_window_to_me_add);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MagnateWindowActivity_.this.addMagnate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_magnate_window_to_me_modify);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MagnateWindowActivity_.this.modifyMagnate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_header_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MagnateWindowActivity_.this.back();
                    }

                }
                );
            }
        }
        ((TitleBar_) titleBar).afterSetContentView_();
        ((GetUserInfo_) getUserInfo).afterSetContentView_();
        ((SetUserInfo_) setUserInfo).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static MagnateWindowActivity_.IntentBuilder_ intent(Context context) {
        return new MagnateWindowActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MagnateWindowActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MagnateWindowActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
