//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.network.request.GetStrangerInfo_;
import cn.sx.decentworld.widget.HackyViewPager;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.handmark.pulltorefresh.library.PullToRefreshScrollView;

public final class NearCardDetailActivity_
    extends NearCardDetailActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_near_card_detail);
    }

    private void init_(Bundle savedInstanceState) {
        getStrangerInfo = GetStrangerInfo_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        ivRealNameOrNickName = ((ImageView) findViewById(id.iv_realname_nickname));
        tvPerAge = ((TextView) findViewById(id.tv_per_age));
        ivLike = ((ImageView) findViewById(id.iv_per_like));
        ivAddFriend = ((ImageView) findViewById(id.iv_add_friend));
        llTalkToStranger = ((LinearLayout) findViewById(id.ll_talk_stranger));
        tvPerJob = ((TextView) findViewById(id.tv_per_job));
        tvFinish = ((TextView) findViewById(id.tv_finish));
        tvWealth = ((TextView) findViewById(id.tv_per_wealth));
        ivDisLike = ((ImageView) findViewById(id.iv_per_dislike));
        ivBack = ((ImageView) findViewById(id.iv_back));
        mRgPerData = ((RadioGroup) findViewById(id.rg_per_data));
        tvPerSign = ((TextView) findViewById(id.tv_per_sign));
        relTitleRoot = ((RelativeLayout) findViewById(id.rel_top_title_root));
        tvOccupation = ((TextView) findViewById(id.tv_occupation));
        tvPerName = ((TextView) findViewById(id.tv_per_name));
        pScrollView = ((PullToRefreshScrollView) findViewById(id.pScrollView));
        tvPerShortIntroduce = ((TextView) findViewById(id.tv_per_short_introduce));
        ivPerSex = ((ImageView) findViewById(id.iv_per_sex));
        tvPerDistance = ((TextView) findViewById(id.tv_per_distance));
        tvPerWorth = ((TextView) findViewById(id.tv_per_worth));
        ivDoubt = ((ImageView) findViewById(id.iv_doubt));
        mPager = ((HackyViewPager) findViewById(id.vp_near_card_detail_pager));
        ((GetStrangerInfo_) getStrangerInfo).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static NearCardDetailActivity_.IntentBuilder_ intent(Context context) {
        return new NearCardDetailActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, NearCardDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public NearCardDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
