//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.ChoceAndTakePictureComponent_;
import cn.sx.decentworld.component.ToastComponent_;
import cn.sx.decentworld.component.ui.PublicWorkComponent_;
import cn.sx.decentworld.widget.ImageViewForGridView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class PublicWorkActivity_
    extends PublicWorkActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_publicwork);
    }

    private void init_(Bundle savedInstanceState) {
        publicWorkComponent = PublicWorkComponent_.getInstance_(this);
        c = ChoceAndTakePictureComponent_.getInstance_(this);
        toast = ToastComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        rb_public_work_friend = ((RadioButton) findViewById(id.rb_public_work_friend));
        rb_public_work_stranger = ((RadioButton) findViewById(id.rb_public_work_stranger));
        rl_public_work_see = ((RelativeLayout) findViewById(id.rl_public_work_see));
        tv_public_work_description = ((TextView) findViewById(id.tv_public_work_description));
        ll_public_work_stranger = ((LinearLayout) findViewById(id.ll_public_work_stranger));
        gv_public_work_pictures = ((ImageViewForGridView) findViewById(id.gv_public_work_pictures));
        ll_public_work_root = ((LinearLayout) findViewById(id.ll_public_work_root));
        tv_public_work_confirm = ((TextView) findViewById(id.tv_public_work_confirm));
        ll_public_work_friend = ((LinearLayout) findViewById(id.ll_public_work_friend));
        rl_public_work_no_see = ((RelativeLayout) findViewById(id.rl_public_work_no_see));
        ((PublicWorkComponent_) publicWorkComponent).afterSetContentView_();
        ((ChoceAndTakePictureComponent_) c).afterSetContentView_();
        ((ToastComponent_) toast).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static PublicWorkActivity_.IntentBuilder_ intent(Context context) {
        return new PublicWorkActivity_.IntentBuilder_(context);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        PublicWorkActivity_.super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  10 :
                PublicWorkActivity_.this.onResult(resultCode, data);
                break;
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PublicWorkActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PublicWorkActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
