//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.component.KeyboardComponent_;
import cn.sx.decentworld.component.ui.RegisterComponent_;
import cn.sx.decentworld.widget.ClearEditText;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class RegisterSetPasswordActivity_
    extends RegisterSetPasswordActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_register_set_password);
    }

    private void init_(Bundle savedInstanceState) {
        keyboardComponent = KeyboardComponent_.getInstance_(this);
        registerComponent = RegisterComponent_.getInstance_(this);
    }

    private void afterSetContentView_() {
        ivPwdIsShow = ((ImageView) findViewById(id.iv_pwd_is_show));
        llRegisterSetPassword = ((LinearLayout) findViewById(id.root_activity_register_set_password));
        tvTitle = ((TextView) findViewById(id.tv_header_title));
        etSign = ((ClearEditText) findViewById(id.cet_sign));
        ivBack = ((ImageView) findViewById(id.iv_back));
        etvPwd = ((EditText) findViewById(id.etv_reset_pwd));
        etRealName = ((ClearEditText) findViewById(id.et_realName));
        btnOk = ((Button) findViewById(id.btn_OK));
        ((KeyboardComponent_) keyboardComponent).afterSetContentView_();
        ((RegisterComponent_) registerComponent).afterSetContentView_();
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static RegisterSetPasswordActivity_.IntentBuilder_ intent(Context context) {
        return new RegisterSetPasswordActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RegisterSetPasswordActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RegisterSetPasswordActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
