//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.id;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.widget.ListViewForScrollView;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class SelectedActivity_
    extends SelectedActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_selected);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        tvDistanceScope = ((TextView) findViewById(id.tv_distance_scope));
        tvMoney = ((TextView) findViewById(id.tv_money));
        btnOk = ((Button) findViewById(id.btn_OK));
        llGirl = ((LinearLayout) findViewById(id.ll_girl));
        lvSelect = ((ListViewForScrollView) findViewById(id.lv_select));
        llContainerAge = ((LinearLayout) findViewById(id.ll_container_age));
        ivBoy = ((ImageView) findViewById(id.iv_boy));
        llContainerWorth = ((LinearLayout) findViewById(id.ll_container_worth));
        ivGirl = ((ImageView) findViewById(id.iv_girl));
        tvWorthScope = ((TextView) findViewById(id.tv_worth_scope));
        tvAgeScope = ((TextView) findViewById(id.tv_age_scope));
        llBoy = ((LinearLayout) findViewById(id.ll_boy));
        llContainerDistance = ((LinearLayout) findViewById(id.ll_container_distance));
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static SelectedActivity_.IntentBuilder_ intent(Context context) {
        return new SelectedActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SelectedActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SelectedActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
