//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.index;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import cn.sx.decentworld.R.layout;

public final class MainFragment_
    extends MainFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        mainFragmentContainer = ((FrameLayout) findViewById(cn.sx.decentworld.R.id.mainFragmentContainer));
        conversationUnreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_unread_msg_number));
        menu_tab_4 = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_4));
        menu_tab1_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab1_tv));
        menu_tab_3 = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_3));
        meUnreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab4_unread_msg_number));
        menu_tab4_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab4_iv));
        menu_tab1_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab1_iv));
        menu_tab2_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab2_iv));
        menu_tab_1 = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_1));
        menu_tab4_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab4_tv));
        findUnreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab3_unread_msg_number));
        contactUnreadLabel = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab2_unread_msg_number));
        menu_tab3_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab3_tv));
        menu_tab_2 = ((RelativeLayout) findViewById(cn.sx.decentworld.R.id.menu_tab_2));
        menu_tab2_tv = ((TextView) findViewById(cn.sx.decentworld.R.id.menu_tab2_tv));
        menu_tab3_iv = ((ImageView) findViewById(cn.sx.decentworld.R.id.menu_tab3_iv));
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_main, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static MainFragment_.FragmentBuilder_ builder() {
        return new MainFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public MainFragment build() {
            MainFragment_ fragment_ = new MainFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
