//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cn.sx.decentworld.fragment.index;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import cn.sx.decentworld.R.layout;
import cn.sx.decentworld.network.request.GetStrangerInfo_;

public final class StrangerFragment_
    extends StrangerFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        getStrangerInfo = GetStrangerInfo_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        ivStrangerMessage = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_stranger_message));
        ivSmallPic = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_small_pic));
        ivSelect = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_select));
        ivBigPic = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_big_pic));
        ivLike = ((ImageView) findViewById(cn.sx.decentworld.R.id.iv_like));
        ((GetStrangerInfo_) getStrangerInfo).afterSetContentView_();
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.main_layout_stranger, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static StrangerFragment_.FragmentBuilder_ builder() {
        return new StrangerFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public StrangerFragment build() {
            StrangerFragment_ fragment_ = new StrangerFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
